### ISSUE TITLE
Problem about class DynamicallyConstistentEndEffectorTrajectory report "the minimization problem hhas no solution!"

### ISSUE THREAD

**Issue by laniakeawhite** [machines-in-motion/reactive_planners#29]
Hello
    I am reading the source code of reactive_planners and trying to modify some parameters of **demo_reactive_planners_bolt_step_adjustment.py** for test.
 It seems both stance leg and swing leg use QP to find the force  as feedforward term.
According to my test:
1. the QP problem for stance leg always have solution
2. the QP problem for swing leg may have no solution from time to time.

Here is what i want to ask bout:
1. Is it ok if QP problem for swing leg have no solution?It seems if no solution,it will use the previous force
2. Why does QP problem for swing leg need to find so many sample point from current time to end time of one step?This may need so much time to find the solution especially at the beginning of one step.Does it possible to just only optimize for one sample point of currrent time?If so,it will save lots of time.

**Comment by Lhumd** [comment]
1) It depends on the trajectory generation algorithm that you are using. If you use a polynomial trajectory, you may need help finding a solution for the problem. If you use our method, it should find the solution but may be too far from the desired landing position. We are aware that the policy doesn't find the solution in some corner cases, but theoretically, it should find the solution, and we are working to find the issue.
2) That's also a choice. We control our robot in 1Khz. That's why we want to solve the solution for every 1ms timestep. Remember that to solve the problem with our approach, we need to find the whole trajectory, so optimizing it for only one sample doesn't give you an optimal solution!
I am going to close it. Feel free to open it if some part of my answer is unclear.
